### ISSUE TITLE
Can't add a caption to the table

### ISSUE THREAD

**Issue by navels** [kyeotic/durandal-grid#5]
Need to add a caption data-part to the view.  Thanks.

**Comment by kyeotic** [comment]
I'm not sure what you mean.

**Comment by navels** [comment]
Try adding a caption to one of your examples:

```
<caption>This is a caption</caption>
```

It does not render in the final view.

**Comment by kyeotic** [comment]
I'll add a data-part for that tomorrow. Or you can add a pull-request for one.

**Comment by navels** [comment]
I'll add a pull-request.  I'm new to git so it'll be good practice :)
